### ISSUE TITLE
Error, starting md4rd

### ISSUE THREAD

**Issue by BuddhiLW** [ahungry/md4rd#31] opened 2021-01-02 12:01 UTC
M-x md4rd RET

And, my *Compile-Log*
 says,

In toplevel form:
md4rd.el:43:1:Error: Symbol's value as variable is void: hierarchy--make

![pic-window-210102-0900-53](https://user-images.githubusercontent.com/59554283/103456871-032fa380-4cd9-11eb-9fa9-a5d6edfebb49.png)

**Comment by ahungry** [comment] 2021-05-26 05:26
Still an issue?

This appears to be a problem with hierarchy mode (I don't seem to have the issue, and it should have installed a proper/working copy as the melpa dependency).

Please re-open if so.

**Comment by knatsakis** [comment] 2021-05-26 09:25
Hi @ahungry, it is still an issue for me.

I have hierarchy-20190425.842 from melpa installed. However, `(require 'hierarchy)` also fails with `(void-variable hierarchy--make)` so maybe it's an issue of the hierarchy package?

What version of hierarchy are you using?

**Comment by ahungry** [comment] 2021-05-26 14:00
Very odd - that's what I have:

hierarchy-20190425.842

**Comment by BuddhiLW** [comment] 2021-05-27 14:40
Here is actually working, now. But, then gain, I'm using EXWM and changed barely all my configs. So, I wouldn't know how to pin point what fixed it.

If I were to guess, I think there must be some package the program depends on to render, which causes the problem. Maybe you have to install something in your machine, via package manager

**Comment by ahungry** [comment] 2021-05-27 18:21
Hmm...I wonder if it's not intended that I use a call to hierarchy--make directly, I forgot that the double dash usually implies it's a "private" function in a given package.

I wonder if there is a "public" one like hierarchy-make or similar that I should be calling instead, or if they just have odd naming conventions in the package.

**Comment by ahungry** [comment] 2021-05-27 18:28
Oh, even more odd, I am not calling that.  I use hierarchy-new which itself is a wrapper around hierarchy--make.

hierarchy--make is a function or macro that ends up defined as a result of their cl-defstruct call in the hierarchy.el package (of which md4rd heavily depends on).

cl-defstruct is defined in cl-macs.el, which is shipped as part of Emacs.

I wonder if the issue is some autoload problem in hierarchy.el, where this isn't getting loaded in time, but that'd be odd since I explicitly `(require 'hierarchy)` in the md4rd package (and hierarchy.el itself does not use any autoloads actually).

Let's close this one until we can reproduce in a minimal setup (of just md4rd and no other init settings), as I believe it's a more user-specific issue involving scope outside of this package.

**Closed as completed by ahungry** 2021-05-27 18:28 UTC

**Comment by knatsakis** [comment] 2021-05-27 21:16
Removing `.emacs.d/elpa/27.1/develop/hierarchy-20190425.842/hierarchy.elc` fixed the issue for me. Weird 🤷🏻‍♂️
